{% set name = "dotmap" %}
{% set version = "1.3.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ae2a8362ab63b2dcb1ebcd73cfcd1a67a8418b3370e15dcd3aeb089c71a55e82

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6

test:
  imports:
    - dotmap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/drgrib/dotmap
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: Ordered, dynamically-expandable dot-access dictionary
  dev_url: https://github.com/drgrib/dotmap
  doc_url: https://github.com/drgrib/dotmap

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
