travis:
  secure:
    BINSTAR_TOKEN: qtSJzVSLSKfuKb53UoWR9ijVOQ8e/6LOAAPSlM0SAsh/zNvRPz1en43yzKhws/xBcbrel0EMOKnskKhs+uF2edDo6em2YSXIoyUurnCU6mz5tHPTp/szz68Z5GOpKcHgPizBKXBk4U6rkj1Fjcw0EWLHm0dDRB1ltIN332NMsfBauAnBqWIKo6RXo7IyozFBU9Ek2QUCq5IBp2ApGl5TN0VGEm9ZSkWc+LiJ5g3fL9P6UI159MMafJH8M07rvajkXBZhTZ63tAj+/Zov0D9IrYlLKEg04Tt0JBp1dSOlSDQg8oVorLNZt6k7Sr/dXsvuZwnOygIXG9djg1ezsxwvw2m9sx6Km7/ah2nawhig9bVomB3AAzsbzV7vr6dqO7h05lnJm2CoHPM7gKWkRyZ23zB57ToArjWm+zEwPWHs5mVXagi/wPGSTYrAyeNPgiC/Ad2/UXGl1iAxw3314Hndnta5NdzzcX/uweD90bFmNp8hHBFRXnC44GMcs3K2OsU7QBEqaGatklqDxGWjK9NTsWjl8yBlsUOssOpKIRjqp5i7Og3dz57pSVtoX7nUWAdisvqboFVOiXEo3G5AFBbi/kxxmfx7EGDGAhIJnaomtWDcisRaKhIRJ6RsUMKt2VgsMKDBGjAqFQRertir60iqaO40vR5/Yi3zfvyBJgO4NNw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
