travis:
  secure:
    BINSTAR_TOKEN: O/DqF3WQrR10heGJReIWj/TeLruv/8vN1rIHiZ7xjRabNis5Nazbt/t8zEhTJYpXSgftv0hqc78zXc2xWaprgMBp5sfCb4CPuSgufarS9brkANFynhT23VwYjuyp1J2Zytm9E5oLZl1WxAg3cEsA8i63Fb4Zd9Vjxo0qQDQWKrrsLuHIceE9pSWWfGJXUz6cQTLHd6TiFxgbVvXb/v0M+hXyJaMUguVwPFaAKxRJtQdzj1f6/nyQF89GBUMkgQLyb5yJBF+BKW3liTOqzEeifKVtQYn/NA6iRra+NxT2XH1gXnw4B6lwiFLTRctdc8KLIN926pCuVuw44zUxRTFZo1MCgxtetZIM3VLupaSoEoowB1EUVBnPcdGe/dx8nT5hBZEkroMluwsk35itCwuUrIwCwTTYnO7DGzUNe2O1QHqGXFbO5AKRlw7euhnqGetcIg2CcTMNO2o0oCFFWupDrsyiLGLCY3SCV+1zm/LxY9KsTokuGuQrpidgUSPATywvT/auE5rPdfAdEc1PYMwu3q81hBpFTGXnyk/TW9zD4ziTquwgEzoYRYgialbk90pWhEvQKnnRN6dASgTh775aWF43IEaZOPpeAC8jaNYIMC6xfw10d2GhP2naBVGMKlj1Xa2+whwmy70g2NWhx742P3LGR5q2WWI10SVndOEHGwg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
